In [1]:
import numpy as np
import pandas as pd

In [28]:
a = np.array([1,3,4])
b = np.array([1,2,4])
c = np.array([[1,2,3],[4,3,2]])
c[1,:]

array([4, 3, 2])

In [16]:
c = pd.DataFrame(a,b)

In [17]:
c

0
1  1
2  3
4  4

In [38]:
d = np.zeros([4,1])

In [45]:
d

array([[1.16801935],
       [1.16801935],
       [1.16801935],
       [1.16801935]])

In [46]:
x = np.random.rand(4)
z = np.random.rand(4)

In [47]:
d = np.dot(x,z)

In [48]:
d

1.0428203331400938

In [51]:
X = np.array([[1,2,3],[4,3,1],[4,5,2],[3,2,4]])
X

array([[1, 2, 3],
       [4, 3, 1],
       [4, 5, 2],
       [3, 2, 4]])

In [80]:
B = np.array([1,3,4,6])


In [81]:
W = np.array([3,2,1])

In [82]:
W_T = np.transpose(W)
W_T.shape

(3,)

In [84]:
Z = np.dot(X,W_T) + B

In [88]:
A = 1/(1 + np.exp(Z))
Y = np.array([1,0,1,0])

In [89]:
A

array([1.67014218e-05, 2.78946809e-10, 6.91440011e-13, 1.02618796e-10])

In [90]:
dz = A-Y

In [3]:
a = np.array([[45,23,45,56],[34,23,21,15],[45,32,12,45]])
a

array([[45, 23, 45, 56],
       [34, 23, 21, 15],
       [45, 32, 12, 45]])

In [5]:
Cal = a.sum(axis=0)
Cal

array([124,  78,  78, 116])

In [9]:
cal = Cal.reshape(1,4)

In [12]:
c = a/cal*100

In [14]:
d = c[1,:]

In [15]:
a + d

array([[72.41935484, 52.48717949, 71.92307692, 68.93103448],
       [61.41935484, 52.48717949, 47.92307692, 27.93103448],
       [72.41935484, 61.48717949, 38.92307692, 57.93103448]])

In [21]:
A = np.random.randn(5,2)
A

array([[ 1.02309757, -0.1538654 ],
       [-0.84117641,  0.01546685],
       [ 0.68883497, -0.4982542 ],
       [-1.33797029, -0.96864209],
       [ 1.0907051 , -1.14463667]])

In [22]:
B = A.T
B

array([[ 1.02309757, -0.84117641,  0.68883497, -1.33797029,  1.0907051 ],
       [-0.1538654 ,  0.01546685, -0.4982542 , -0.96864209, -1.14463667]])

In [20]:
np.dot(A,A.T)

array([[ 0.83865024,  0.09476128, -0.58228325,  0.11812366, -0.0935939 ],
       [ 0.09476128,  3.93019528,  1.93247615,  0.18551757,  0.61481651],
       [-0.58228325,  1.93247615,  1.42306163,  0.00576311,  0.38382632],
       [ 0.11812366,  0.18551757,  0.00576311,  0.02420058,  0.01428878],
       [-0.0935939 ,  0.61481651,  0.38382632,  0.01428878,  0.11023243]])

In [2]:
A = np.array([[1,2,4],[3,4,5]])

In [6]:
Y = np.array([1,0,1])
K = 0

In [8]:
K = A^(Y)*(1-A)^(1-Y)

In [9]:
K

array([[ 1,  3, -7],
       [-3,  5, -7]], dtype=int32)