In [5]:
import nltk as nl
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
from collections import Counter

In [9]:
nl.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Vishnu\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [10]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [11]:
train = pd.read_csv("traintw.csv")
test = pd.read_csv("testtw.csv")

In [26]:
words = train.tweet


NameError: name 'append' is not defined

In [19]:
train.head(3)

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty

# Calculation of words and char length

In [47]:
train['word_count'] = train['tweet'].apply(lambda x: len(str(x).split(" ")))
Word_count=np.array(train['word_count'])
Word_count

array([21, 22,  5, ..., 15, 13,  8], dtype=int64)

In [48]:
train['char_count'] = train['tweet'].str.len() ## this also includes spaces
train[['tweet','char_count']].head()

tweet  char_count
0   @user when a father is dysfunctional and is s...         102
1  @user @user thanks for #lyft credit i can't us...         122
2                                bihday your majesty          21
3  #model   i love u take with u all the time in ...          86
4             factsguide: society now    #motivation          39

In [49]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Vishnu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [50]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

train['stopwords'] = train['tweet'].apply(lambda x: len([x for x in x.split() if x in stop]))
train[['stopwords','tweet']].head()

stopwords                                              tweet
0         10   @user when a father is dysfunctional and is s...
1          5  @user @user thanks for #lyft credit i can't us...
2          1                                bihday your majesty
3          5  #model   i love u take with u all the time in ...
4          1             factsguide: society now    #motivation

In [51]:
train['hastags'] = train['tweet'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))
Hastags = np.array(train['hastags'])
Hastags

array([1, 3, 0, ..., 0, 4, 0], dtype=int64)

In [52]:
train['numerics'] = train['tweet'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
Numerics = np.array(train['numerics'])
Numerics

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [53]:
#to check the frequency
Counter(Numerics)

Counter({0: 29739, 1: 1964, 2: 216, 3: 33, 4: 9, 6: 1})

In [54]:
train['upper'] = train['tweet'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
Upper = np.array(train['upper'])
Upper
print(Counter(Upper))

Counter({0: 31887, 1: 62, 2: 9, 4: 3, 3: 1})


In [55]:
train['tweet'] = train['tweet'].apply(lambda x: " ".join(x.lower() for x in x.split()))
train['tweet'].head()

0    @user when a father is dysfunctional and is so...
1    @user @user thanks for #lyft credit i can't us...
2                                  bihday your majesty
3    #model i love u take with u all the time in ur...
4                  factsguide: society now #motivation
Name: tweet, dtype: object

In [56]:
train['tweet'] = train['tweet'].str.replace('[^\w\s]','')
train['tweet'].head()

0    user when a father is dysfunctional and is so ...
1    user user thanks for lyft credit i cant use ca...
2                                  bihday your majesty
3    model i love u take with u all the time in urð...
4                    factsguide society now motivation
Name: tweet, dtype: object

In [57]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(...)
 |      S.__format__(format_spec) -> str
 |      
 |      Return a formatted version of S as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getatt

In [60]:
train['tweet'] = train['tweet'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
train['tweet'].head()

0    user father dysfunctional selfish drags kids d...
1    user user thanks lyft credit cant use cause do...
2                                       bihday majesty
3                model love u take u time urð ðððð ððð
4                        factsguide society motivation
Name: tweet, dtype: object